version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: mynginx
    ports:
      - "8080:80"  # → http://localhost:8080 でアクセス
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/usr/share/nginx/html:ro